const KEY='monitoring-note-v2';
const oldKey='monitoring-note-v1';
const defaults={users:[
 {id:'a',name:'Aさん',startDate:'2026-09-01',birthday:'1990-08-12',office:'ひだまり相談支援センター',consultant:'山田さん'},
 {id:'b',name:'Bさん',startDate:'2026-06-10',birthday:'1985-09-20',office:'みどり相談支援事業所',consultant:'佐藤さん'},
 {id:'c',name:'Cさん',startDate:'2026-08-05',birthday:'1994-06-03',office:'つむぎ相談室',consultant:'田中さん'}
],records:[]};
let loaded=JSON.parse(localStorage.getItem(KEY)||'null');
if(!loaded){const old=JSON.parse(localStorage.getItem(oldKey)||'null');loaded=old?{users:old.users.map(u=>({...u,startDate:u.startDate||'',birthday:u.birthday||'',office:u.office||'',consultant:u.consultant||''})),records:old.records||[]}:defaults}
let db=loaded,page='home',editing=null,userEditing=null;
const save=()=>localStorage.setItem(KEY,JSON.stringify(db));
const now=new Date(); let viewYear=now.getFullYear(),viewMonth=now.getMonth()+1;
const ym=(y,m)=>y*12+(m-1); const fromYm=n=>({year:Math.floor(n/12),month:n%12+1});
function schedule(u,fromYear=viewYear-2,toYear=viewYear+2){
 if(!u.startDate)return (u.months||[]).flatMap(m=>Array.from({length:toYear-fromYear+1},(_,i)=>({year:fromYear+i,month:m,type:'定期'})));
 const s=new Date(u.startDate+'T00:00:00'); if(Number.isNaN(+s))return [];
 const initial=ym(s.getFullYear(),s.getMonth()+1)+1; let out=[{...fromYm(initial),type:'初回'}];
 if(u.birthday){const b=new Date(u.birthday+'T00:00:00');const anchor=b.getMonth()+1;for(let y=fromYear-1;y<=toYear+1;y++)for(let k=0;k<4;k++){let n=ym(y,anchor)+k*3;let d=fromYm(n);if(n>initial&&d.year>=fromYear&&d.year<=toYear)out.push({...d,type:'定期'})}}
 return out.filter((x,i,a)=>a.findIndex(z=>z.year===x.year&&z.month===x.month)===i).sort((a,b)=>ym(a.year,a.month)-ym(b.year,b.month));
}
function targetInfo(u,y,m){return schedule(u,y-1,y+1).find(x=>x.year===y&&x.month===m)}
function monthUsers(y,m){return db.users.filter(u=>targetInfo(u,y,m))}
function rec(y,m,id){return db.records.find(r=>r.year==y&&r.month==m&&r.userId==id)}
function previousRec(y,m,id){const n=ym(y,m);return db.records.filter(r=>r.userId===id&&ym(+r.year,+r.month)<n).sort((a,b)=>ym(+b.year,+b.month)-ym(+a.year,+a.month))[0]}
function nextTarget(u,y=now.getFullYear(),m=now.getMonth()+1){return schedule(u,y-1,y+3).find(x=>ym(x.year,x.month)>=ym(y,m))}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function nav(){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page))}
function render(){nav();const a=document.querySelector('#app');if(page==='home')a.innerHTML=home();if(page==='users')a.innerHTML=users();if(page==='history')a.innerHTML=history();if(page==='monitor')a.innerHTML=monitor();if(page==='userEdit')a.innerHTML=userEdit();bind()}
function personMeta(u){return (u.office||u.consultant)?`<div class="contact">☘ ${esc(u.office||'相談事業所 未登録')}${u.consultant?` <span>｜ ${esc(u.consultant)}</span>`:''}</div>`:''}
function home(){let y=now.getFullYear(),m=now.getMonth()+1,us=monthUsers(y,m),done=us.filter(u=>rec(y,m,u.id)).length,p=us.length?Math.round(done/us.length*100):0;return `<div class="hero card"><div class="row"><div><div class="eyebrow">THIS MONTH</div><h3>${m}月のモニタリング</h3></div><b>${done} / ${us.length} 完了</b></div><div class="progress"><i style="width:${p}%"></i></div><div class="muted">完了率 ${p}%　<span class="spark">✦</span> 小さな変化を、安心につなげよう</div></div><h2>今月の対象者</h2>${us.length?us.map(u=>{let r=rec(y,m,u.id),t=targetInfo(u,y,m);return `<div class="card usercard"><div class="row"><span class="pill">${r?'✓ 完了':t?.type==='初回'?'初回':'今月'}</span><span class="muted small">${t?.type||''}</span></div><h2>${esc(u.name)}</h2>${personMeta(u)}${r?`<div class="doneLine">✓ ${esc(r.date)} に完了</div><button class="ghost start" data-id="${u.id}">記録を見る</button>`:`<button class="primary start" data-id="${u.id}">モニタリングする →</button>`}</div>`}).join(''):'<div class="empty card">今月の対象者はいません 🌿</div>'}`}
function users(){return `<div class="row"><div><div class="eyebrow">PEOPLE</div><h2>利用者</h2></div><button class="primary" id="addUser">＋ 新規登録</button></div>${db.users.map(u=>{let n=nextTarget(u);return `<div class="card"><div class="row"><div><h3>${esc(u.name)}</h3>${personMeta(u)}<div class="muted small next">次回：${n?`${n.year}年${n.month}月（${n.type}）`:'設定を確認してください'}</div></div><button class="ghost editUser" data-id="${u.id}">編集</button></div></div>`}).join('')}`}
function history(){let us=monthUsers(viewYear,viewMonth),done=us.filter(u=>rec(viewYear,viewMonth,u.id)).length,p=us.length?Math.round(done/us.length*100):0;let opts=Array.from({length:12},(_,i)=>`<option value="${i+1}" ${viewMonth==i+1?'selected':''}>${i+1}月</option>`).join('');return `<div class="eyebrow">HISTORY</div><h2>モニタリング履歴</h2><div class="card historyHead"><div class="monthTitle"><button class="ghost" id="prev">‹</button><b>${viewYear}年</b><select id="monthSel">${opts}</select><button class="ghost" id="next">›</button></div><div class="rate">${p}<small>%</small></div><div class="muted center">${done} / ${us.length}人 完了</div><div class="progress"><i style="width:${p}%"></i></div></div>${us.map(u=>{let r=rec(viewYear,viewMonth,u.id),t=targetInfo(u,viewYear,viewMonth);return `<div class="card"><div class="row"><div><span class="pill">${t?.type||'対象'}</span><h3 class="historyName">${r?'✓ ':''}${esc(u.name)}</h3>${personMeta(u)}<div class="${r?'muted':'notdone'}">${r?`${esc(r.date)} 完了`:'未完了'}</div></div>${r?`<button class="ghost viewRec" data-id="${u.id}">内容を見る</button>`:''}</div></div>`}).join('')||'<div class="empty card">この月の対象者はいません</div>'}`}
const fields=['体調','食事・水分','排泄','睡眠','その他'];
function monitor(){let u=db.users.find(x=>x.id===editing);if(!u)return '<div class="empty">利用者が見つかりません</div>';let old=rec(viewYear,viewMonth,editing),prev=previousRec(viewYear,viewMonth,editing);return `<button class="ghost" id="back">‹ 戻る</button><div class="monitorTitle"><div class="eyebrow">MONITORING</div><h2>${esc(u.name)}</h2>${personMeta(u)}<div class="muted">${viewYear}年${viewMonth}月の記録</div></div>${prev?`<details class="previous card"><summary>前回の記録を見る <span>${prev.year}年${prev.month}月</span></summary><div class="prevGrid">${fields.map((f,i)=>`<div class="prevItem"><b>${f}</b><span class="prevStatus">${esc(prev.items?.[i]?.status||'記録なし')}</span><p>${esc(prev.items?.[i]?.memo||'メモなし')}</p></div>`).join('')}</div></details>`:`<div class="previous card muted">🌱 前回の記録はまだありません（初回モニタリング）</div>`}<form id="form">${fields.map((f,i)=>`<div class="card itemCard"><div class="compareLabel">${prev?`前回：<b>${esc(prev.items?.[i]?.status||'記録なし')}</b>${prev.items?.[i]?.memo?`「${esc(prev.items[i].memo)}」`:''}`:'初回記録'}</div><label>${f}</label><div class="choices"><button type="button" class="choice ${old?.items?.[i]?.status==='変化なし'?'active':''}" data-i="${i}" data-v="変化なし">変化なし</button><button type="button" class="choice change ${old?.items?.[i]?.status==='変化あり'?'active':''}" data-i="${i}" data-v="変化あり">変化あり</button></div><label class="muted small">今回のメモ（任意）</label><textarea name="memo${i}" placeholder="前回からの変化や気づいたこと">${esc(old?.items?.[i]?.memo||'')}</textarea><input type="hidden" name="status${i}" value="${esc(old?.items?.[i]?.status||'')}"></div>`).join('')}<button class="primary saveBtn">保存して完了 ✓</button></form>`}
function userEdit(){let u=db.users.find(x=>x.id===userEditing)||{};return `<button class="ghost" id="backUsers">‹ 利用者一覧</button><div class="eyebrow formEye">PROFILE</div><h2>${userEditing?'利用者情報を編集':'新規利用者登録'}</h2><div class="card profileForm"><form id="userForm"><label>利用者名</label><input name="name" required value="${esc(u.name||'')}" placeholder="例：Aさん"><div class="two"><div><label>利用開始日</label><input type="date" name="startDate" required value="${esc(u.startDate||'')}"></div><div><label>誕生日</label><input type="date" name="birthday" required value="${esc(u.birthday||'')}"></div></div><div class="ruleNote">🌿 初回は利用開始の翌月。その後は誕生月を基準に3か月おきで自動設定します。</div><label>相談事業所</label><input name="office" value="${esc(u.office||'')}" placeholder="例：ひだまり相談支援センター"><label>相談員名</label><input name="consultant" value="${esc(u.consultant||'')}" placeholder="例：山田さん"><button class="primary saveBtn">${userEditing?'変更を保存':'登録する'}</button></form></div>${userEditing?`<button class="danger" id="deleteUser">この利用者を削除</button>`:''}`}
function bind(){document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()});document.querySelectorAll('.start').forEach(b=>b.onclick=()=>{editing=b.dataset.id;viewYear=now.getFullYear();viewMonth=now.getMonth()+1;page='monitor';render()});document.querySelectorAll('.viewRec').forEach(b=>b.onclick=()=>{editing=b.dataset.id;page='monitor';render()});let ms=document.querySelector('#monthSel');if(ms)ms.onchange=e=>{viewMonth=+e.target.value;render()};let prev=document.querySelector('#prev');if(prev)prev.onclick=()=>{viewMonth--;if(viewMonth<1){viewMonth=12;viewYear--}render()};let next=document.querySelector('#next');if(next)next.onclick=()=>{viewMonth++;if(viewMonth>12){viewMonth=1;viewYear++}render()};let back=document.querySelector('#back');if(back)back.onclick=()=>{page='history';render()};document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{let i=b.dataset.i;document.querySelectorAll(`.choice[data-i="${i}"]`).forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector(`[name=status${i}]`).value=b.dataset.v});let form=document.querySelector('#form');if(form)form.onsubmit=e=>{e.preventDefault();let fd=new FormData(form),items=fields.map((_,i)=>({status:fd.get('status'+i)||'変化なし',memo:fd.get('memo'+i).trim()}));db.records=db.records.filter(r=>!(r.year==viewYear&&r.month==viewMonth&&r.userId==editing));db.records.push({year:viewYear,month:viewMonth,userId:editing,date:new Date().toLocaleDateString('ja-JP'),items});save();page='home';render()};let add=document.querySelector('#addUser');if(add)add.onclick=()=>{userEditing=null;page='userEdit';render()};document.querySelectorAll('.editUser').forEach(b=>b.onclick=()=>{userEditing=b.dataset.id;page='userEdit';render()});let bu=document.querySelector('#backUsers');if(bu)bu.onclick=()=>{page='users';render()};let uf=document.querySelector('#userForm');if(uf)uf.onsubmit=e=>{e.preventDefault();let fd=new FormData(uf),data={name:fd.get('name').trim(),startDate:fd.get('startDate'),birthday:fd.get('birthday'),office:fd.get('office').trim(),consultant:fd.get('consultant').trim()};if(userEditing){Object.assign(db.users.find(x=>x.id===userEditing),data)}else db.users.push({id:Date.now().toString(36),...data});save();page='users';render()};let del=document.querySelector('#deleteUser');if(del)del.onclick=()=>{if(confirm('この利用者と記録を削除しますか？')){db.users=db.users.filter(x=>x.id!==userEditing);db.records=db.records.filter(x=>x.userId!==userEditing);save();page='users';render()}}}
save();render();
