const KEY='monitoring-note-v1';
const defaults={users:[{id:'a',name:'Aさん',months:[9]},{id:'b',name:'Bさん',months:[9]},{id:'c',name:'Cさん',months:[9]}],records:[]};
let db=JSON.parse(localStorage.getItem(KEY)||'null')||defaults;let page='home',editing=null;
const save=()=>localStorage.setItem(KEY,JSON.stringify(db)); const now=new Date(); let viewYear=now.getFullYear(),viewMonth=now.getMonth()+1;
function monthUsers(y,m){return db.users.filter(u=>u.months.includes(m))} function rec(y,m,id){return db.records.find(r=>r.year==y&&r.month==m&&r.userId==id)}
function nav(){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page))}
function render(){nav(); const a=document.querySelector('#app'); if(page==='home')a.innerHTML=home();if(page==='users')a.innerHTML=users();if(page==='history')a.innerHTML=history();if(page==='monitor')a.innerHTML=monitor();bind()}
function home(){let us=monthUsers(now.getFullYear(),now.getMonth()+1),done=us.filter(u=>rec(now.getFullYear(),now.getMonth()+1,u.id)).length,p=us.length?Math.round(done/us.length*100):0;return `<div class="card"><div class="row"><h3>${now.getMonth()+1}月のモニタリング</h3><b>${done} / ${us.length} 完了</b></div><div class="progress"><i style="width:${p}%"></i></div><div class="muted">完了率 ${p}%</div></div><h2>今月の対象者</h2>${us.length?us.map(u=>`<div class="card usercard"><span class="pill">${rec(now.getFullYear(),now.getMonth()+1,u.id)?'完了':'対象'}</span><h2>${u.name}</h2>${rec(now.getFullYear(),now.getMonth()+1,u.id)?`<div class="muted">今月のモニタリング完了</div>`:`<button class="primary start" data-id="${u.id}">モニタリングする →</button>`}</div>`).join(''):'<div class="empty">今月の対象者はいません</div>'}`}
function users(){return `<div class="row"><h2>利用者</h2><button class="primary" id="addUser">＋ 追加</button></div>${db.users.map(u=>`<div class="card"><div class="row"><div><h3>${u.name}</h3><div class="muted small">対象月：${u.months.sort((a,b)=>a-b).map(x=>x+'月').join('・')}</div></div><button class="ghost editUser" data-id="${u.id}">編集</button></div></div>`).join('')}`}
function history(){let us=monthUsers(viewYear,viewMonth),done=us.filter(u=>rec(viewYear,viewMonth,u.id)).length,p=us.length?Math.round(done/us.length*100):0;let opts=Array.from({length:12},(_,i)=>`<option value="${i+1}" ${viewMonth==i+1?'selected':''}>${i+1}月</option>`).join('');return `<h2>モニタリング履歴</h2><div class="card"><div class="monthTitle"><button class="ghost" id="prev">‹</button><b>${viewYear}年</b><select id="monthSel">${opts}</select><button class="ghost" id="next">›</button></div><div class="row" style="margin-top:18px"><b>完了率 ${p}%</b><b>${done} / ${us.length}人 完了</b></div><div class="progress"><i style="width:${p}%"></i></div></div>${us.map(u=>{let r=rec(viewYear,viewMonth,u.id);return `<div class="card"><div class="row"><div><h3>${r?'✓ ':''}${u.name}</h3><div class="${r?'muted':'notdone'}">${r?`${r.date} 完了`:'未完了'}</div></div>${r?`<button class="ghost viewRec" data-id="${u.id}">内容</button>`:''}</div></div>`}).join('')||'<div class="empty">この月の対象者はいません</div>'}`}
const fields=['体調','食事・水分','排泄','睡眠'];
function monitor(){let u=db.users.find(x=>x.id===editing),old=rec(viewYear,viewMonth,editing);return `<button class="ghost" id="back">‹ 戻る</button><h2>${u.name}｜モニタリング</h2><div class="muted">各項目を選び、必要なところだけメモを残します。</div><form id="form">${fields.map((f,i)=>`<div class="card"><label>${f}</label><div class="choices"><button type="button" class="choice ${old?.items?.[i]?.status==='変化なし'?'active':''}" data-i="${i}" data-v="変化なし">変化なし</button><button type="button" class="choice ${old?.items?.[i]?.status==='変化あり'?'active':''}" data-i="${i}" data-v="変化あり">変化あり</button></div><label class="muted small">メモ（任意）</label><textarea name="memo${i}" placeholder="気づいたことを入力">${old?.items?.[i]?.memo||''}</textarea><input type="hidden" name="status${i}" value="${old?.items?.[i]?.status||''}"></div>`).join('')}<button class="primary" style="width:100%">保存して完了</button></form>`}
function bind(){document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()});document.querySelectorAll('.start').forEach(b=>b.onclick=()=>{editing=b.dataset.id;viewYear=now.getFullYear();viewMonth=now.getMonth()+1;page='monitor';render()});document.querySelectorAll('.viewRec').forEach(b=>b.onclick=()=>{editing=b.dataset.id;page='monitor';render()});
let ms=document.querySelector('#monthSel');if(ms)ms.onchange=e=>{viewMonth=+e.target.value;render()};let prev=document.querySelector('#prev');if(prev)prev.onclick=()=>{viewMonth--;if(viewMonth<1){viewMonth=12;viewYear--}render()};let next=document.querySelector('#next');if(next)next.onclick=()=>{viewMonth++;if(viewMonth>12){viewMonth=1;viewYear++}render()};let back=document.querySelector('#back');if(back)back.onclick=()=>{page='history';render()};document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{let i=b.dataset.i;document.querySelectorAll(`.choice[data-i="${i}"]`).forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector(`[name=status${i}]`).value=b.dataset.v});let form=document.querySelector('#form');if(form)form.onsubmit=e=>{e.preventDefault();let fd=new FormData(form),items=fields.map((_,i)=>({status:fd.get('status'+i)||'変化なし',memo:fd.get('memo'+i).trim()}));db.records=db.records.filter(r=>!(r.year==viewYear&&r.month==viewMonth&&r.userId==editing));db.records.push({year:viewYear,month:viewMonth,userId:editing,date:new Date().toLocaleDateString('ja-JP'),items});save();page='home';render()};
let add=document.querySelector('#addUser');if(add)add.onclick=()=>editUser();document.querySelectorAll('.editUser').forEach(b=>b.onclick=()=>editUser(b.dataset.id))}
function editUser(id){let u=db.users.find(x=>x.id===id),name=prompt('利用者名',u?.name||'');if(!name)return;let raw=prompt('モニタリング対象月をカンマ区切りで入力（例：1,3,9,12）',u?.months.join(',')||String(now.getMonth()+1));let months=(raw||'').split(',').map(Number).filter(x=>x>=1&&x<=12);if(u){u.name=name;u.months=[...new Set(months)]}else db.users.push({id:Date.now().toString(36),name,months:[...new Set(months)]});save();render()}
render();
